language: node_js

node_js:
  - "5.3"

cache:
  directories:
    - node_modules
    - test/integration/node_modules

addons:
  postgresql: "9.4"

sudo: required

services:
  - postgresql

env:
  - NODE_ENV=test

before_script: npm run compile

script:
  - npm run test:unit
  - ./prepareIntegrationTest.sh && npm run test:integration

